api_platform:
    title: Symfony API Base
    version: 1.0.0
    formats:
        json: ["application/json"]
    error_formats:
        json: ["application/json"] 
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        pagination_enabled: true
        pagination_items_per_page: 10
        # Paginación configurable por el cliente:
        pagination_client_items_per_page: true
        pagination_items_per_page_parameter_name: limit
        pagination_maximum_items_per_page: 9999
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

when@prod:
    api_platform:
        # Deshabilitar documentación en producción
        enable_swagger: false
        enable_swagger_ui: false
        enable_re_doc: false
        enable_docs: false
        enable_entrypoint: false
