<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Entity\EntitySchema;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260101000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schema base: usuario, configuracion_sistema, usuario_log_accion, messenger_messages.';
    }

    public function up(Schema $schema): void
    {
        $s = EntitySchema::MAIN;

        $this->addSql("CREATE SCHEMA IF NOT EXISTS {$s}");
        $this->addSql('CREATE EXTENSION IF NOT EXISTS unaccent');

        $this->addSql("CREATE TABLE {$s}.usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSONB NOT NULL, password VARCHAR(255) NOT NULL, dni INT DEFAULT NULL, apellido VARCHAR(50) NOT NULL, nombre VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL, fecha_alta DATE NOT NULL, fecha_baja DATE DEFAULT NULL, ultimo_acceso TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, cantidad_accesos SMALLINT DEFAULT NULL, last_user_app_id SMALLINT DEFAULT NULL, auth_code VARCHAR(30) DEFAULT NULL, trusted_version INT DEFAULT NULL, profile JSON DEFAULT NULL, PRIMARY KEY (id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON {$s}.usuario (username)");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.id IS 'ID Usuario.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.username IS 'Nombre del Usuario.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.roles IS 'Roles del Usuario.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.password IS 'Password del Usuario.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.dni IS 'DNI del Usuario.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.apellido IS 'Utilizado para mostrar el Usuario Logueado.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.nombre IS 'Utilizado para mostrar el usuario Logueado.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.email IS 'Dirección del Correo Electrónico.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.fecha_alta IS 'Fecha de Alta.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.fecha_baja IS 'Fecha de Baja.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.ultimo_acceso IS 'Fecha del último acceso.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.cantidad_accesos IS 'Cantidad de accesos efectuados por el usuario.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.last_user_app_id IS 'ID del usuario que generó el alta o última modific. en el Registro.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.auth_code IS 'Código de autenticación 2FA.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.trusted_version IS 'Versionado de código 2FA.'");
        $this->addSql("COMMENT ON COLUMN {$s}.usuario.profile IS 'Profile del usuario. Usado para guardar configuraciones propias del usuario.'");

        $this->addSql("CREATE TABLE {$s}.configuracion_sistema (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, clave VARCHAR(255) NOT NULL, valor VARCHAR(255) NOT NULL, observaciones TEXT DEFAULT NULL, last_user_app_id INT DEFAULT NULL, PRIMARY KEY (id))");
        $this->addSql("COMMENT ON TABLE {$s}.configuracion_sistema IS 'Informacion de variables de configuración del sistema.'");
        $this->addSql("COMMENT ON COLUMN {$s}.configuracion_sistema.id IS 'ID registro de configuracion'");
        $this->addSql("COMMENT ON COLUMN {$s}.configuracion_sistema.clave IS 'Clave del registro'");
        $this->addSql("COMMENT ON COLUMN {$s}.configuracion_sistema.valor IS 'Valor del Registro'");
        $this->addSql("COMMENT ON COLUMN {$s}.configuracion_sistema.observaciones IS 'Observación del Registro'");
        $this->addSql("COMMENT ON COLUMN {$s}.configuracion_sistema.last_user_app_id IS 'ID del usuario que generó el alta o última modific. en el Registro'");

        $this->addSql("CREATE TABLE {$s}.usuario_log_accion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_hora TIMESTAMP(0) WITH TIME ZONE NOT NULL, ip VARCHAR(40) DEFAULT NULL, accion VARCHAR(255) DEFAULT NULL, usuario_id INT NOT NULL, impersonate_to_id INT DEFAULT NULL, PRIMARY KEY (id))");
        $this->addSql("CREATE INDEX IDX_ULA_USUARIO ON {$s}.usuario_log_accion (usuario_id)");
        $this->addSql("CREATE INDEX IDX_ULA_IMPERSONATE ON {$s}.usuario_log_accion (impersonate_to_id)");
        $this->addSql("COMMENT ON TABLE {$s}.usuario_log_accion IS 'Auditoría de Accesos de Usuarios al Sistema'");
        $this->addSql("ALTER TABLE {$s}.usuario_log_accion ADD CONSTRAINT FK_ULA_USUARIO FOREIGN KEY (usuario_id) REFERENCES {$s}.usuario (id) NOT DEFERRABLE");
        $this->addSql("ALTER TABLE {$s}.usuario_log_accion ADD CONSTRAINT FK_ULA_IMPERSONATE FOREIGN KEY (impersonate_to_id) REFERENCES {$s}.usuario (id)");

        $this->addSql("CREATE TABLE {$s}.messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))");
        $this->addSql("CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON {$s}.messenger_messages (queue_name, available_at, delivered_at, id)");
    }

    public function down(Schema $schema): void
    {
        $s = EntitySchema::MAIN;

        $this->addSql("ALTER TABLE {$s}.usuario_log_accion DROP CONSTRAINT FK_ULA_USUARIO");
        $this->addSql("ALTER TABLE {$s}.usuario_log_accion DROP CONSTRAINT FK_ULA_IMPERSONATE");
        $this->addSql("DROP TABLE {$s}.messenger_messages");
        $this->addSql("DROP TABLE {$s}.usuario_log_accion");
        $this->addSql("DROP TABLE {$s}.configuracion_sistema");
        $this->addSql("DROP TABLE {$s}.usuario");
        $this->addSql('DROP EXTENSION IF EXISTS unaccent');
        $this->addSql("DROP SCHEMA IF EXISTS {$s}");
    }
}
