<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702123250 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_schema.detalle_integracion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, can_int INT NOT NULL, motivo VARCHAR(80) DEFAULT NULL, last_user_app_id INT DEFAULT NULL, tipo_marca_id INT DEFAULT NULL, integracion_id INT NOT NULL, vocal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1DC48B51572A5A88 ON app_schema.detalle_integracion (tipo_marca_id)');
        $this->addSql('CREATE INDEX IDX_1DC48B513CFB7FAA ON app_schema.detalle_integracion (integracion_id)');
        $this->addSql('CREATE INDEX IDX_1DC48B51B0210CE2 ON app_schema.detalle_integracion (vocal_id)');
        $this->addSql('CREATE TABLE app_schema.expediente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_exp INT DEFAULT NULL, anio INT DEFAULT NULL, cuij VARCHAR(255) DEFAULT NULL, caratula VARCHAR(255) NOT NULL, estado VARCHAR(1) NOT NULL, last_user_app_id INT DEFAULT NULL, presidencia_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2106A73596AAE5E ON app_schema.expediente (presidencia_id)');
        $this->addSql('CREATE TABLE app_schema.fuero (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion VARCHAR(255) NOT NULL, cod_fuero VARCHAR(4) DEFAULT NULL, estado VARCHAR(1) NOT NULL, last_user_app_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE app_schema.integracion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha DATE NOT NULL, sala INT NOT NULL, tipo VARCHAR(255) NOT NULL, observacion VARCHAR(255) DEFAULT NULL, estado VARCHAR(1) NOT NULL, nro_integra INT DEFAULT NULL, anio_integra INT DEFAULT NULL, fecha_reintegro DATE DEFAULT NULL, last_user_app_id INT DEFAULT NULL, presidencia_id INT NOT NULL, expediente_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D92EF2B596AAE5E ON app_schema.integracion (presidencia_id)');
        $this->addSql('CREATE INDEX IDX_7D92EF2B4BF37E4E ON app_schema.integracion (expediente_id)');
        $this->addSql('CREATE TABLE app_schema.licencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_desde DATE NOT NULL, fecha_hasta DATE NOT NULL, motivo VARCHAR(255) NOT NULL, estado VARCHAR(1) NOT NULL, last_user_app_id INT DEFAULT NULL, vocal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38F98E40B0210CE2 ON app_schema.licencia (vocal_id)');
        $this->addSql('CREATE TABLE app_schema.presidencia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tribu VARCHAR(50) NOT NULL, cant_sala INT NOT NULL, voc_sala INT NOT NULL, cant_sala_pro INT DEFAULT NULL, fec_inst DATE NOT NULL, id_inst INT NOT NULL, email VARCHAR(40) NOT NULL, estado VARCHAR(1) NOT NULL, cod_org INT NOT NULL, licencia INT DEFAULT NULL, sort_comun SMALLINT NOT NULL, sort_ad_hoc SMALLINT NOT NULL, sort_cinco SMALLINT NOT NULL, sort_comp SMALLINT NOT NULL, cod_fuero VARCHAR(2) DEFAULT NULL, last_user_app_id INT DEFAULT NULL, voc_otro_fuero INT DEFAULT NULL, resta INT DEFAULT NULL, sorteo_aleatorio INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE app_schema.tipo_marca (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descripcion VARCHAR(50) NOT NULL, letra VARCHAR(1) DEFAULT NULL, estado VARCHAR(1) NOT NULL, last_user_app_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE app_schema.vocal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sala INT NOT NULL, nombre VARCHAR(30) NOT NULL, numero INT NOT NULL, estado VARCHAR(1) NOT NULL, ad_hoc INT NOT NULL, orden INT NOT NULL, asigna INT NOT NULL, integra INT NOT NULL, email VARCHAR(40) DEFAULT NULL, fec_baja DATE DEFAULT NULL, mot_baja VARCHAR(20) DEFAULT NULL, voc_propio INT NOT NULL, last_user_app_id INT DEFAULT NULL, fuero_id INT NOT NULL, presidencia_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CB509917EC985FE8 ON app_schema.vocal (fuero_id)');
        $this->addSql('CREATE INDEX IDX_CB509917596AAE5E ON app_schema.vocal (presidencia_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE app_schema.detalle_integracion ADD CONSTRAINT FK_1DC48B51572A5A88 FOREIGN KEY (tipo_marca_id) REFERENCES app_schema.tipo_marca (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_schema.detalle_integracion ADD CONSTRAINT FK_1DC48B513CFB7FAA FOREIGN KEY (integracion_id) REFERENCES app_schema.integracion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_schema.detalle_integracion ADD CONSTRAINT FK_1DC48B51B0210CE2 FOREIGN KEY (vocal_id) REFERENCES app_schema.vocal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_schema.expediente ADD CONSTRAINT FK_D2106A73596AAE5E FOREIGN KEY (presidencia_id) REFERENCES app_schema.presidencia (id)');
        $this->addSql('ALTER TABLE app_schema.integracion ADD CONSTRAINT FK_7D92EF2B596AAE5E FOREIGN KEY (presidencia_id) REFERENCES app_schema.presidencia (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_schema.integracion ADD CONSTRAINT FK_7D92EF2B4BF37E4E FOREIGN KEY (expediente_id) REFERENCES app_schema.expediente (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_schema.licencia ADD CONSTRAINT FK_38F98E40B0210CE2 FOREIGN KEY (vocal_id) REFERENCES app_schema.vocal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_schema.vocal ADD CONSTRAINT FK_CB509917EC985FE8 FOREIGN KEY (fuero_id) REFERENCES app_schema.fuero (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_schema.vocal ADD CONSTRAINT FK_CB509917596AAE5E FOREIGN KEY (presidencia_id) REFERENCES app_schema.presidencia (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE app_schema.messenger_messages');
        $this->addSql('ALTER TABLE app_schema.usuario ADD presidencia_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE app_schema.usuario ADD CONSTRAINT FK_185FEEDB596AAE5E FOREIGN KEY (presidencia_id) REFERENCES app_schema.presidencia (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_185FEEDB596AAE5E ON app_schema.usuario (presidencia_id)');
        $this->addSql('COMMENT ON COLUMN app_schema.usuario_log_accion.usuario_id IS \'ID Usuario.\'');
        $this->addSql('COMMENT ON COLUMN app_schema.usuario_log_accion.impersonate_to_id IS \'ID Usuario.\'');
        $this->addSql('ALTER INDEX app_schema.idx_ula_usuario RENAME TO IDX_FB53B66ADB38439E');
        $this->addSql('ALTER INDEX app_schema.idx_ula_impersonate RENAME TO IDX_FB53B66AD1A8743B');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_schema.messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON app_schema.messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE app_schema.detalle_integracion DROP CONSTRAINT FK_1DC48B51572A5A88');
        $this->addSql('ALTER TABLE app_schema.detalle_integracion DROP CONSTRAINT FK_1DC48B513CFB7FAA');
        $this->addSql('ALTER TABLE app_schema.detalle_integracion DROP CONSTRAINT FK_1DC48B51B0210CE2');
        $this->addSql('ALTER TABLE app_schema.expediente DROP CONSTRAINT FK_D2106A73596AAE5E');
        $this->addSql('ALTER TABLE app_schema.integracion DROP CONSTRAINT FK_7D92EF2B596AAE5E');
        $this->addSql('ALTER TABLE app_schema.integracion DROP CONSTRAINT FK_7D92EF2B4BF37E4E');
        $this->addSql('ALTER TABLE app_schema.licencia DROP CONSTRAINT FK_38F98E40B0210CE2');
        $this->addSql('ALTER TABLE app_schema.vocal DROP CONSTRAINT FK_CB509917EC985FE8');
        $this->addSql('ALTER TABLE app_schema.vocal DROP CONSTRAINT FK_CB509917596AAE5E');
        $this->addSql('DROP TABLE app_schema.detalle_integracion');
        $this->addSql('DROP TABLE app_schema.expediente');
        $this->addSql('DROP TABLE app_schema.fuero');
        $this->addSql('DROP TABLE app_schema.integracion');
        $this->addSql('DROP TABLE app_schema.licencia');
        $this->addSql('DROP TABLE app_schema.presidencia');
        $this->addSql('DROP TABLE app_schema.tipo_marca');
        $this->addSql('DROP TABLE app_schema.vocal');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE app_schema.usuario DROP CONSTRAINT FK_185FEEDB596AAE5E');
        $this->addSql('DROP INDEX app_schema.IDX_185FEEDB596AAE5E');
        $this->addSql('ALTER TABLE app_schema.usuario DROP presidencia_id');
        $this->addSql('COMMENT ON COLUMN app_schema.usuario_log_accion.usuario_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN app_schema.usuario_log_accion.impersonate_to_id IS \'\'');
        $this->addSql('ALTER INDEX app_schema.idx_fb53b66ad1a8743b RENAME TO idx_ula_impersonate');
        $this->addSql('ALTER INDEX app_schema.idx_fb53b66adb38439e RENAME TO idx_ula_usuario');
    }
}
